# Generated by Django 5.0.3 on 2024-03-15 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_profile_uid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
